# Generated by Django 4.0.4 on 2023-04-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_nature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
    ]
