# Generated by Django 4.1.7 on 2023-04-22 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_oku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 16, 57, 22, 819580, tzinfo=datetime.timezone.utc)),
        ),
    ]
