# Generated by Django 4.0.4 on 2023-04-10 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_oku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 18, 28, 19, 376039, tzinfo=utc)),
        ),
    ]
