# Generated by Django 4.0.4 on 2023-04-17 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_oku', '0004_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 10, 28, 43, 526226, tzinfo=utc)),
        ),
    ]
