# Generated by Django 4.0.4 on 2023-04-21 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_oku', '0008_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 14, 17, 5, 871501, tzinfo=utc)),
        ),
    ]
